### PR TITLE
fix tonvm dependencies

### PR DESCRIPTION
**Pull request by klim0v**

### CODE REVIEW

**Comment by cmxog** [comment]
@klim0v apologies for missing this PR, and thank you for sending it in.

I just double-checked `tonvm` and it looks like we don't use Core there; any particular reason why you needed to add it?

P.S. Also, for future reference, we auto-generate opam files from `dune-project`. Opam files have a note about this:

```
# This file is generated by dune, edit dune-project instead
```

**Comment by klim0v** [comment]
with a clean install, my installation of `tonvm` package is interrupted. if you install it after installing `core` package, the problem does not occur

**Comment by cmxog** [comment]
Thank you for bringing this to our attention. There has indeed been a problem. I've just fixed it on the main branch (4b06c98). The dependency on `core` was not, in fact, coming through `tonvm` but it was rather an artifact of how `dune` works in terms of designating libraries to packages. Tests were mistakenly assigned to `tonvm` as well as they didn't have a clear designation.

**Comment by klim0v** [comment]
Thank you for your work ❤️

**Pull request closed without merging**
