### PR TITLE
Add parametrized type construction syntax

### LINKED ISSUE #12: Add parametrized type construction syntax
```
let MyType(T: Type) = type {a: T};
let t = MyType(Int257) { a: 1 };
```

### PR DESCRIPTION
**Pull request by p0lunin**
Resolves #12

Stuck with problem of disambiguation between `code_block` and `type_construction` (in case of anonymous type construction) rules.

### CODE REVIEW

**Comment by cmxog** [comment]
Cherry-picked parametric construction at 8e89d7d6960bf61c5f988d43aebe49536e81c662 with `Caml.print_string` debugging removed, this will need rebasing.

Thank you!

**Comment by cmxog** [comment]
Partially addressed in 193371a but I am going to do a bit more work to iterate faster and better on this.

**Comment by cmxog** [comment]
Should we close this one?

**Comment by p0lunin** [comment]
Closed since we decide to not add anonymous struct for now.

**Pull request closed without merging**
